language: erlang
otp_release:
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
script: "rm -rf deps ebin && make deps && make && make eunit"
branches:
  only:
       - master
notifications:
  email:
      - 738819904@qq.com
                                